### ISSUE TITLE
[Bug] The extension stopped working

### ISSUE THREAD

**Issue by romanskorobagatko** [hardingadonis/hash-pasted-image#12]
It stopped renaming pasted images, I also tried creating a fresh new vault - still doesn’t rename files.

M1 mac, Sonoma 14.6.1

**Comment by hardingadonis** [comment]
@romanskorobagatko, can you give me the videos as evidence? I do not have any Apple devices.

**Comment by romanskorobagatko** [comment]
@hardingadonis https://www.dropbox.com/scl/fi/uewlggg6s4ct3c0qdj4iu/Screen-Recording-2024-08-22-15-36-01.mp4?rlkey=loqfnxbfvrd58fh6scu71xlln&raw=1

**Comment by hardingadonis** [comment]
@romanskorobagatko thanks for your support. I will log this bug and fix it next week.

**Comment by hardingadonis** [comment]
Hi @romanskorobagatko, I fixed this bug, please check the new version.

**Comment by romanskorobagatko** [comment]
@hardingadonis I just checked it and it works now, thank you!

**Comment by hardingadonis** [comment]
@romanskorobagatko no problem, can u give me a star?

**Comment by romanskorobagatko** [comment]
@hardingadonis done, thanks for reminding me to do that.
